"""create admin table

Revision ID: 901c4e5b3ebc
Revises: 6f2eebab3220
Create Date: 2026-01-16 13:07:42.328719+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '901c4e5b3ebc'
down_revision: Union[str, Sequence[str], None] = '6f2eebab3220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_user_id'), 'admin', ['user_id'], unique=True)
    op.add_column('user_photo_settings', sa.Column('aspect_ratio', sa.String(length=16), nullable=False))
    op.add_column('user_photo_settings', sa.Column('resolution', sa.String(length=8), nullable=False))
    op.add_column('user_photo_settings', sa.Column('output_format', sa.String(length=8), nullable=False))
    op.drop_column('user_photo_settings', 'fmt')
    op.drop_column('user_photo_settings', 'size')
    op.drop_column('user_photo_settings', 'quality')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_photo_settings', sa.Column('quality', sa.VARCHAR(length=16), nullable=False))
    op.add_column('user_photo_settings', sa.Column('size', sa.VARCHAR(length=32), nullable=False))
    op.add_column('user_photo_settings', sa.Column('fmt', sa.VARCHAR(length=16), nullable=False))
    op.drop_column('user_photo_settings', 'output_format')
    op.drop_column('user_photo_settings', 'resolution')
    op.drop_column('user_photo_settings', 'aspect_ratio')
    op.drop_index(op.f('ix_admin_user_id'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
